language: julia
julia:
  - 1.3
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project -e 'using Pkg; pkg"registry add https://github.com/sisl/Registry"'
  - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';
